"Changes: Sprites":
- '**/*.rsi/*.png'

"Changes: Map":
- 'Resources/Maps/*.yml'
- 'Resources/Prototypes/Maps/*.yml'

"Changes: UI":
- '**/*.xaml*'

"Changes: Localization":
- 'Resources/Locale/**/*.ftl'

"Changes: Audio":
- 'Resources/Audio/**/*.ogg'

"Changes: Migration":
- 'Resources/migration.yml'

"No C#":
- all: ["!**/*.cs"]

