#Wizard outfit startingGear definitions.
- type: startingGear
  id: WizardBlueGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitColorDarkBlue
    back: ClothingBackpackFilled
    head: ClothingHeadHatWizard
    neck: ClothingNeckCloakChristmas #RADIUM_CHRISTMAS
    outerClothing: ClothingOuterWizard
    shoes: ClothingShoesWizard
    id: PassengerPDA
    ears: ClothingHeadsetService
  innerClothingSkirt: ClothingUniformJumpskirtColorDarkBlue
  satchel: ClothingBackpackSatchelFilled
  duffelbag: ClothingBackpackDuffelFilled

- type: startingGear
  id: WizardRedGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitColorRed
    back: ClothingBackpackFilled
    head: ClothingHeadHatRedwizard
    outerClothing: ClothingOuterWizardRed
    shoes: ClothingShoesWizard
    neck: ClothingNeckCloakChristmas #RADIUM_CHRISTMAS
    id: PassengerPDA
    ears: ClothingHeadsetService
  innerClothingSkirt: ClothingUniformJumpskirtColorRed
  satchel: ClothingBackpackSatchelFilled
  duffelbag: ClothingBackpackDuffelFilled

- type: startingGear
  id: WizardVioletGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitColorPurple
    back: ClothingBackpackFilled
    head: ClothingHeadHatVioletwizard
    outerClothing: ClothingOuterWizardViolet
    shoes: ClothingShoesWizard
    neck: ClothingNeckCloakChristmas #RADIUM_CHRISTMAS
    id: PassengerPDA
    ears: ClothingHeadsetService
  innerClothingSkirt: ClothingUniformJumpskirtColorPurple
  satchel: ClothingBackpackSatchelFilled
  duffelbag: ClothingBackpackDuffelFilled

- type: startingGear
  id: WizardHardsuitGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitColorPurple
    back: ClothingBackpackFilled
    outerClothing: ClothingOuterHardsuitWizard
    shoes: ClothingShoesWizard
    neck: ClothingNeckCloakChristmas #RADIUM_CHRISTMAS
    id: PassengerPDA
    ears: ClothingHeadsetService
  innerClothingSkirt: ClothingUniformJumpskirtColorPurple
  satchel: ClothingBackpackSatchelFilled
  duffelbag: ClothingBackpackDuffelFilled
