- type: job
  id: Surgeon
  name: job-name-surgeon
  description: job-description-surgeon
  playTimeTracker: JobSurgeon
  requirements:
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 21600 # 6 Hours Radium-RoleTime
  startingGear: SurgeonGear
  icon: "JobIconSurgeon"
  supervisors: job-supervisors-cmo
  access:
  - Medical
  - Maintenance
  extendedAccess:
  - Chemistry
  #start-radium: currency
  minBankBalance: 150
  maxBankBalance: 250
  wageDepartment: Medical
  wage: 50
  #end-radium: currency

- type: startingGear
  id: SurgeonGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitMedicalDoctor
    back: ClothingBackpackMedicalFilled
    shoes: ClothingShoesColorWhite
    head: ClothingHeadHatSurgcapBlue
    mask: ClothingMaskSterile
    gloves: ClothingHandsGlovesNitrile
    outerClothing: ClothingOuterCoatLab
    id: SurgeonPDA
    ears: ClothingHeadsetMedical
    belt: ClothingBeltMedicalFilled
  innerClothingSkirt: ClothingUniformJumpskirtMedicalDoctor
  satchel: ClothingBackpackSatchelMedicalFilled
  duffelbag: ClothingBackpackDuffelMedicalFilled

