- type: entity
  id: PaperPrinterCircuitboard
  parent: BaseMachineCircuitboard
  name: плата принтера
  description: A machine printed circuit board for a printer.
  components:
    - type: Sprite
      state: service
    - type: MachineBoard
      prototype: PaperPrinter
      requirements:
        MatterBin: 2
        Manipulator: 2
      tagRequirements:
        GlassBeaker:
          Amount: 2
          DefaultPrototype: Beaker
          ExamineName: Glass Beaker
