name: "Labels: Untriaged"

on:
  issues:
    types: [opened]

jobs:
  add_label:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
    - uses: actions-ecosystem/action-add-labels@v1
      with:
        labels: "Status: Untriaged"
